name: ShadowVM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: shadowvm
      run: docker build . --file Dockerfile --tag is-a.kvm:$(date +%s)
